#!/bin/bash

function deploy_spx {
	if [ ${unclean} -eq 0 ] ; then
		sudo /apollo/bin/runCommand -a Deactivate -a Preactivate -a Activate -e Spot-ExchangeService-lizyang ;
	else 
		/apollo/env/Spot-ExchangeService-lizyang/ApolloCmd/Deactivate/100ShutdownProcessManager
		/apollo/env/Spot-ExchangeService-lizyang/ApolloCmd/Activate/100RestartProcessManager
	fi
}

# check operating system
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

optget="optget"
if [ $machine == "Mac" ]
then
	optget="/usr/local/bin/getopt"
elif [ $machine == "Linux" ]
then
	optget="getopt"
fi

if [ $machine == "Mac" ] ; then echo "Can't deploy any service on laptop" >&2 ; exit 1 ; fi

# read the options
TEMP=`"${optget}" -o w:u --long workspace:unclean -- "$@"`
eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# extract options and their arguments into variables.
unclean=0
while true ; do
    case "$1" in
        -w|--workspace)
        	workspace=$2 ; shift 2 ;;
        -u|--unclean)
			unclean=1 ; shift 1 ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

case "${workspace}" in
	spx)		deploy_spx ;;
	capmon)		deploy_capmon ;;
	spws)		deploy_spws ;;
	*)			echo "No workspace ..." ;;
esac
